### ISSUE TITLE
Bump hspec dependency

### ISSUE THREAD

**Issue by abbradar** [jcristovao/newtype-generics#13]
It builds with 2.4.1.

**Comment by sjakobi** [comment]
Related to https://github.com/jcristovao/newtype-generics/pull/12?

**Comment by abbradar** [comment]
Yes, indeed - I haven't checked PRs before reporting. Should I close this?

**Comment by sjakobi** [comment]
> Should I close this?

I guess one PR or issue to track this should be enough.
