### ISSUE TITLE
missing instance for `Identity` (which can be found in base)

### ISSUE THREAD

**Issue by imz** [jcristovao/newtype-generics#2]
In the documentation, it is claimed there are instances for the types from `base`.

But I miss an instance for `Identity` from Control.Monad.Identity (which is actually defined and imported from [Data.Functor.Identity](http://hackage.haskell.org/package/base-4.8.0.0/docs/Data-Functor-Identity.html) from `base`).

Can it be added without problems?

**Comment by imz** [comment]
My quick workaround in my code for now is like this:

    {-# LANGUAGE StandaloneDeriving, DeriveGeneric #-}
    
    import Control.Newtype
    import Control.Monad.Identity
    import GHC.Generics
    
    deriving instance Generic (Identity a)
    instance Newtype (Identity a)

Then I can write something like:

    unsafeFromString =
        under Identity 
            (\v' -> do (String t) <- v'
    	           return t)

(as an implemntation of
[my (bad) idea](http://www.reddit.com/r/haskell/comments/38kl9z/thoughts_on_xlambdado_syntax/crwadmk?context=3)
how to suppress a warning about a non-exhaustive pattern match). It's
here just to serve as an example.

**Comment by sjakobi** [comment]
Thanks for the suggestion! :+1: Fixed in https://github.com/jcristovao/newtype-generics/commit/3b803ac0cb87b214411a5cb6b52e4cac300b1c75.

**Comment by sjakobi** [comment]
Published in [v0.5.1](https://hackage.haskell.org/package/newtype-generics-0.5.1).
