### ISSUE TITLE
Support base-0.4.9 in the hackage package.

### ISSUE THREAD

**Issue by jchia** [jcristovao/newtype-generics#8]

**Comment by clinty** [comment]
I think you mean base 4.10

**Comment by jchia** [comment]
I actually meant release a hackage package version supporting base-0.4.9. newtype-generics-0.4.1 requires 	base (>=4.5 && <4.9).

**Comment by sjakobi** [comment]
This issue prevents recent versions of `MemoTrie` from building with GHC-8.0, [forcing stackage to use a version with broken haddocks](https://github.com/fpco/stackage/issues/1999). :(

**Comment by clinty** [comment]
It builds at least if you just tweak the upper bounds on base.

**Comment by sjakobi** [comment]
@jcristovao: I see that this issue has been fixed on master. What's blocking a release? Can we help?

**Comment by jcristovao** [comment]
Mainly lack of time on my part, for which I am sorry!

I do welcome more contributors, so if anybody else wants to share the responsibility of maintaining this here and in hackage, do let me know.

For now I've udpated a new version to hackage, sorry for keeping everybody waiting.

**Comment by sjakobi** [comment]
> Mainly lack of time on my part, for which I am sorry!

I guess this can happen to all of us, no reason to be sorry! :)

> I do welcome more contributors, so if anybody else wants to share the responsibility of maintaining this here and in hackage, do let me know.

I've started "watching" this repo and will try to help out in the future. At this point I'm entirely unfamiliar with the codebase and know very little about Haskell generics, so I'm not sure if I can be of much help.

> For now I've udpated a new version to hackage, sorry for keeping everybody waiting.

Thanks a lot!
